<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PigeonPost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PigeonPost.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Pontifex" Version="0.1.2-dev.0" />
    <PackageReference Include="Pontifex.Transport.Direct" Version="0.1.1-dev.0" />
    <PackageReference Include="Pontifex.Transport.Tcp" Version="0.1.2-dev.0" />
    <PackageReference Include="Scriba" Version="0.2.3-dev.0" />
    <PackageReference Include="Scriba.JsonFactory" Version="0.2.1-dev.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PigeonPost.Tun\PigeonPost.Tun.csproj" />
    <ProjectReference Include="..\PigeonPost.Tun.Virtual\PigeonPost.Tun.Virtual.csproj" />
    <ProjectReference Include="..\PigeonPost.Bridge\PigeonPost.Bridge.csproj" />
  </ItemGroup>
</Project>
