services:
  pigeonpost:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      additional_contexts:
        - nugets=/Users/fyodor/Development/nugets
    image: pigeonpost:latest
    container_name: pigeonpost-server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      TUN_NAME: tun0
      TUN_IP: 10.0.0.1
      PEER_IP: 10.0.0.2
    ports:
      - "9000:9000"
    command: --role server --tun tun0 --url tcp|0.0.0.0:9000/30
    restart: unless-stopped
